on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        description: tag name (format must be vX.Y.Z or vX.Y.Z.rc<N>)

name: release

permissions:
  contents: write
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Create tag
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.inputs.tag_name }}
          TAGGER_NAME: ${{ github.actor }}
          TAGGER_EMAIL: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$GITHUB_REPOSITORY/git/tags \
          -f "tag=$TAG_NAME" \
          -f "message=release $TAG_NAME" \
          -f "object=$GITHUB_SHA" \
          -f "type=commit" \
          -f "tagger[name]=$TAGGER_NAME" \
          -f "tagger[email]=$TAGGER_EMAIL"