on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        description: tag name (format must be vX.Y.Z or vX.Y.Z.rc<N>)

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Create tag
        run: git tag -s -a ${{ github.event.inputs.tag_name }} -m ${{ github.event.inputs.tag_name }}
      - name: Push tag
        run: git push --tags